services:
  plant-disease-api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: plant-disease-detection-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro
      - ./api:/app/api:ro
    environment:
      - PYTHONPATH=/app
      - TF_CPP_MIN_LOG_LEVEL=2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
